[[redirects]]
  from = "/"
  to = "/aex-portfolio.html"
  status = 200

[[headers]]
  for = "*.mp4"
  [headers.values]
    Cache-Control = "public, max-age=31536000"
    Accept-Ranges = "bytes"
    Content-Type = "video/mp4"

[[headers]]
  for = "*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"
